version: "3"

services:
  web:
    build: ./
    ports:
      - "80:80"
    environment:
        - DB_URL=mongodb://db/myTestDB

  db:
      image: mongo
      ports:
          - "27017:27017"
      volumes:
          - taskdb:/data/db

volumes:
    taskdb:
